Add midnight workflow
scalecube/.github pull request #41
Opened 2024-10-08 13:56 UTC by RostyslavBaldovskyi

Link: https://github.com/exberry-io/docs/issues/1514

Behavior:
- In repos default branch is develop, meaning scheduler will build develop
- If scheduled build is failed it will create ticket - https://github.com/exberry-io/docs/issues/...
- If ticket was created new one will not be created
- If build was success previously opened issue about failed build will be closed
- Ticket has link to the build as a description and 'ScheduledBuildFail' label
- If closed it will have "Closed due to success build" comment
- Scheduled builds will not do deploys (push)
- Each repo should have "scheduler" property, it is not inherited from the parent

Example:

// Has intentionally broken test
https://github.com/exberry-io/iam-service/actions/runs/11235838718

// Made tests to work again
https://github.com/exberry-io/iam-service/actions/runs/11236318175

// This task was created and then closed due to recovered build
https://github.com/exberry-io/docs/issues/2541

2024-10-08 15:22 UTC, artem-v commented
@RostyslavBaldovskyi here it's said: 

> Scheduled builds will not do deploys (push)

But after looking at 

> // Made tests to work again (ticket closed)
https://github.com/exberry-io/iam-service/actions/runs/11237958557

It looks like robokit deployed service.

2024-10-08 15:24 UTC, artem-v commented
> // This task was created and then closed due to recovered build
https://github.com/exberry-io/docs/issues/2542

Why tasks are being created as they are created by @ronenhamias ? Can't we have special user, for example like `exberry-ci` or `exberry-bot`.  Looping in @nicolaicinali, maybe he has some idea in this regard too.

2024-10-08 15:28 UTC, nicolaicinali commented
> > // This task was created and then closed due to recovered build
> > [exberry-io/docs#2542](https://github.com/exberry-io/docs/issues/2542)
> 
> Another question: why tasks are being created as they are created by @ronenhamias? Can't we have special user, for example like `exberry-ci` or `exberry-bot`.
> 
> Looping in @nicolaicinali, maybe he has some idea in this regard too.

Most likely it depends on the GitHub token, especially who is the owner of the token. GH CI uses `ORGANIZATION_TOKEN` GH token. Maybe it was created by Ronen?...
in order to have the right answer we need to understand what steps have been executed when the GH issue have been created and closed.

2024-10-08 16:14 UTC, RostyslavBaldovskyi commented
> @RostyslavBaldovskyi here it's said:
> 
> > Scheduled builds will not do deploys (push)
> 
> But after looking at
> 
> > // Made tests to work again (ticket closed)
> > https://github.com/exberry-io/iam-service/actions/runs/11237958557
> 
> It looks like robokit deployed service.

Will check

2024-10-08 16:24 UTC, RostyslavBaldovskyi commented
Pushed a fix for robokit to iam-service. 
Will not change cron for now, tomorrow we`ll see if it works. 
It should run at midnight UTC

2024-10-09 07:31 UTC, RostyslavBaldovskyi commented
It worked: https://github.com/exberry-io/iam-service/actions/runs/11246029727

2024-10-09 07:46 UTC, RostyslavBaldovskyi commented
> we need to understand what steps have been executed when the GH issue have been created and closed.

Steps are defined in file which is changed:
- notify_failure
- close_issue

It uses `secrets.ORGANIZATION_TOKEN`

2024-10-09 08:14 UTC, artem-v requested changes

2024-10-09 08:14 UTC, artem-v commented on .github/workflows/ci.yml
> +            }
Let's  have new line at the end. Plz add new line.

2024-10-09 08:14 UTC, artem-v commented on .github/workflows/ci.yml
> +
Remove one empty line

2024-10-09 08:30 UTC, artem-v approved these changes
LGTM

2024-10-09 08:35 UTC, merged